"""add category column to expenses below description

Revision ID: 8ae526bcf638
Revises: 8f2a888f62a8
Create Date: 2026-08-08 12:11:00.474215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae526bcf638'
down_revision: Union[str, Sequence[str], None] = '8f2a888f62a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'category')
    # ### end Alembic commands ###
